version: '2'

services:
  postgres:
    image: postgres:11.12-alpine
    container_name: postgres
    environment:
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
      - "POSTGRES_DB=voicebot"
    ports:
      - "5432:5432"  # credentials (docker:docker)
